### ISSUE TITLE
Failed validation rule: Maxumim size <= 200 characters

### ISSUE THREAD

**Issue by rmagsayo** [nHapiNET/nHapi#105]
Hi!
I am trying to parse an ORU^R01 file with ED data but I always had this error "Failed validation rule: Maxumim size <= 200 characters" keep bugging me. Can you please shade light on how to resolve this issue. Many thanks and all the best. Below are the errors I was able to record. Any help is much appreciated.
Regards,
Roche

NHapi.Base.DataTypeException was unhandled
  FieldPosition=-1
  HResult=-2146233088
  Message=Failed validation rule: Maxumim size <= 200 characters
  SegmentRepetition=-1
  Source=NHapi.Base
  StackTrace:
       at NHapi.Base.Model.Varies.fixOBX5(ISegment segment, IModelClassFactory factory)
       at NHapi.Base.Parser.PipeParser.Parse(ISegment destination, String segment, EncodingCharacters encodingChars)
       at NHapi.Base.Parser.PipeParser.DoParse(String message, String version)
       at NHapi.Base.Parser.ParserBase.Parse(String message, String version)
       at NHapi.Base.Parser.ParserBase.Parse(String message)
       at ConsoleApplication2.Program.Main(String[] args) in d:\DOCS\Visual Studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 45
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by Usualdosage** [comment]
Updated to allow max string length for ED fields.

**Comment by milkshakeuk** [comment]
@Usualdosage 

Have u checked the Hl7 specifications to see if the length has a limit of 200?

The point of NHapi is to adhere to the official hl7 standards.

**Comment by Usualdosage** [comment]
For ED, ED is one of the few examples where an ID value is taken from an externally derived code system (IANA mime types in this case). The conformance length is 32: Applications SHALL be able to handle mime types up to a length of 32. Applications can choose to handle more if desired.

**Comment by albert-wong** [comment]
Im still getting this error using v3.1.1
```
Failed validation rule: Maximum size <= 200 characters
 at NHapi.Base.Model.Varies.FixOBX5(ISegment segment, IModelClassFactory factory, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.PipeParser.Parse(ISegment destination, String segment, EncodingCharacters encodingChars, Int32 repetition, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.PipeParser.Parse(IMessage message, String string, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.PipeParser.DoParse(String message, String version, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.ParserBase.Parse(String message, String version, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.ParserBase.Parse(String message, ParserOptions parserOptions)\r\n   at NHapi.Base.Parser.ParserBase.Parse(String message
 ```
 Any help on how I can allow base64 strings processing?
